### ISSUE TITLE
why only copying is used? Isn't it better for backups to use VM Export?

### ISSUE THREAD

**Issue by mrPsycho** [Digressive/HyperV-Backup-Utility#3]
Hello,

as i understand how it works - you just copy and paste all the stuff. 
also, it is needed that VM will be stopped. 

drawbacks are obvious: 
* if hyper-v server fails - restoring will be kinda tricky. It will be needed to create VM and point VHD's or, change config files to fix paths. 
* VM has to be stopped.

but, as i know exporting allows to get exact copy of VM in one file, which can be easily restored...

or i'm totally wrong?

**Comment by Digressive** [comment]
Hi,

Exporting doesn't give you an exact copy of a VM in one file, it just performs a copy of all the files needed for the VM.

Normally you would and should just use VM export, but in situations where you can't this script will enable you to still perform a VM Export type function. The VM needs to be shutdown because otherwise the files are locked.

Restoring is simple, you point Hyper-V to a folder of a good backup and perform an import.
